version: '3.7'
services:
  backend:
    build:
      context: .
      target: development
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/backend
    restart: unless-stopped
    environment:
      - PORT=4000
      - DB_URI=mongodb://mongodb:27017/social
      - DB_NAME=social
    depends_on:
      - mongodb
      - postgresql

  mongodb:
    image: mongo:latest
    volumes:
      - ./.data/mongodb:/data/db
    ports:
      - 27018:27017
    restart: unless-stopped

  postgresql:
    image: postgres:12.3-alpine
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mydbpostgres

volumes:
  postgres:
  mongodb:
