version: '3.7'
services:
  backend:
    build:
      context: .
      target: development
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/backend
    restart: unless-stopped
    environment:
      - PORT=4000
      - DB_URI=mongodb://mongodb:27017
      - DB_NAME=social
  mongodb:
    image: mongo:latest
    volumes:
      - ./.data:/data/db
    ports:
      - 27018:27017
    restart: unless-stopped
